# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

addons:
  mariadb: '10.1'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev lcov rubygems-integration
  - gem install lcoveralls

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - make test
  - make mad_tests_coverage

after_success:
  - lcoveralls
