# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

addons:
  mariadb: '10.1'

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev lcov rubygems-integration g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - gem install lcoveralls
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -uroot test < tests/test.sql

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - make test
  - make mad_tests_coverage
  - make quantile_tests_coverage
  - sudo make install
  - mysql -uroot < ../install.sql
  - cd ../tests
  - ./mariadb_test.sh
  - cd ../

after_success:
  - lcoveralls
