# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install lcov rubygems
  - gem install lcoveralls
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make test
  - make mad_tests_coverage

after_success:
  - lcoveralls
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
