CREATE OR REPLACE AGGREGATE FUNCTION mad RETURNS REAL SONAME 'libmad_udf.so';
CREATE OR REPLACE AGGREGATE FUNCTION median RETURNS REAL SONAME 'libmad_udf.so';
CREATE OR REPLACE AGGREGATE FUNCTION quantile RETURNS REAL SONAME 'libquantile_udf.so';
